// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | HeroSlice
  | ManifiestoSlice
  | ModalidadesSlice
  | ProcesoSlice
  | TerritorioSlice
  | DetalleEditorialSlice
  | ConfianzaSlice
  | ContactoSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/* -------------------------------------------------------------------------- */
/* Hero Slice                                                                  */
/* -------------------------------------------------------------------------- */

export interface HeroSliceDefaultPrimary {
  background_image: prismic.ImageField<never>;
  headline: prismic.RichTextField;
  scroll_cue_label: prismic.KeyTextField;
}

export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

type HeroSliceVariation = HeroSliceDefault;

export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/* -------------------------------------------------------------------------- */
/* Manifiesto Slice                                                            */
/* -------------------------------------------------------------------------- */

export interface ManifiestoSliceDefaultPrimary {
  eyebrow: prismic.KeyTextField;
  statement: prismic.RichTextField;
  support: prismic.RichTextField;
}

export type ManifiestoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ManifiestoSliceDefaultPrimary>,
  never
>;

type ManifiestoSliceVariation = ManifiestoSliceDefault;

export type ManifiestoSlice = prismic.SharedSlice<
  "manifiesto",
  ManifiestoSliceVariation
>;

/* -------------------------------------------------------------------------- */
/* Modalidades Slice                                                           */
/* -------------------------------------------------------------------------- */

export interface ModalidadesSliceDefaultPrimaryModalidadesItem {
  image: prismic.ImageField<never>;
  name: prismic.RichTextField;
  description: prismic.RichTextField;
  tags: prismic.KeyTextField;
}

export interface ModalidadesSliceDefaultPrimary {
  eyebrow: prismic.KeyTextField;
  section_title: prismic.RichTextField;
  modalidades: prismic.GroupField<
    Simplify<ModalidadesSliceDefaultPrimaryModalidadesItem>
  >;
}

export type ModalidadesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ModalidadesSliceDefaultPrimary>,
  never
>;

type ModalidadesSliceVariation = ModalidadesSliceDefault;

export type ModalidadesSlice = prismic.SharedSlice<
  "modalidades",
  ModalidadesSliceVariation
>;

/* -------------------------------------------------------------------------- */
/* Proceso Slice                                                               */
/* -------------------------------------------------------------------------- */

export interface ProcesoSliceDefaultPrimaryStepsItem {
  number: prismic.KeyTextField;
  title: prismic.RichTextField;
  description: prismic.RichTextField;
}

export interface ProcesoSliceDefaultPrimary {
  eyebrow: prismic.KeyTextField;
  section_title: prismic.RichTextField;
  steps: prismic.GroupField<Simplify<ProcesoSliceDefaultPrimaryStepsItem>>;
}

export type ProcesoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProcesoSliceDefaultPrimary>,
  never
>;

type ProcesoSliceVariation = ProcesoSliceDefault;

export type ProcesoSlice = prismic.SharedSlice<"proceso", ProcesoSliceVariation>;

/* -------------------------------------------------------------------------- */
/* Territorio Slice                                                            */
/* -------------------------------------------------------------------------- */

export interface TerritorioSliceDefaultPrimary {
  image: prismic.ImageField<never>;
  caption: prismic.RichTextField;
  location_label: prismic.KeyTextField;
}

export type TerritorioSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TerritorioSliceDefaultPrimary>,
  never
>;

type TerritorioSliceVariation = TerritorioSliceDefault;

export type TerritorioSlice = prismic.SharedSlice<
  "territorio",
  TerritorioSliceVariation
>;

/* -------------------------------------------------------------------------- */
/* DetalleEditorial Slice                                                      */
/* -------------------------------------------------------------------------- */

export interface DetalleEditorialSliceDefaultPrimary {
  eyebrow: prismic.KeyTextField;
  headline: prismic.RichTextField;
  body: prismic.RichTextField;
  image: prismic.ImageField<never>;
  image_position: prismic.SelectField<"left" | "right">;
}

export type DetalleEditorialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DetalleEditorialSliceDefaultPrimary>,
  never
>;

type DetalleEditorialSliceVariation = DetalleEditorialSliceDefault;

export type DetalleEditorialSlice = prismic.SharedSlice<
  "detalle_editorial",
  DetalleEditorialSliceVariation
>;

/* -------------------------------------------------------------------------- */
/* Confianza Slice                                                             */
/* -------------------------------------------------------------------------- */

export interface ConfianzaSliceDefaultPrimaryPillarsItem {
  label: prismic.KeyTextField;
  text: prismic.RichTextField;
}

export interface ConfianzaSliceDefaultPrimary {
  eyebrow: prismic.KeyTextField;
  statement: prismic.RichTextField;
  pillars: prismic.GroupField<Simplify<ConfianzaSliceDefaultPrimaryPillarsItem>>;
}

export type ConfianzaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ConfianzaSliceDefaultPrimary>,
  never
>;

type ConfianzaSliceVariation = ConfianzaSliceDefault;

export type ConfianzaSlice = prismic.SharedSlice<
  "confianza",
  ConfianzaSliceVariation
>;

/* -------------------------------------------------------------------------- */
/* Contacto Slice                                                              */
/* -------------------------------------------------------------------------- */

export interface ContactoSliceDefaultPrimary {
  eyebrow: prismic.KeyTextField;
  headline: prismic.RichTextField;
  intro: prismic.RichTextField;
  submit_label: prismic.KeyTextField;
  success_message: prismic.RichTextField;
  legal_note: prismic.RichTextField;
}

export type ContactoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactoSliceDefaultPrimary>,
  never
>;

type ContactoSliceVariation = ContactoSliceDefault;

export type ContactoSlice = prismic.SharedSlice<
  "contacto",
  ContactoSliceVariation
>;

/* -------------------------------------------------------------------------- */
/* RichText Slice (existing)                                                   */
/* -------------------------------------------------------------------------- */

export interface RichTextSliceDefaultPrimary {
  content: prismic.RichTextField;
}

export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

type RichTextSliceVariation = RichTextSliceDefault;

export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ManifiestoSlice,
      ManifiestoSliceDefaultPrimary,
      ManifiestoSliceVariation,
      ManifiestoSliceDefault,
      ModalidadesSlice,
      ModalidadesSliceDefaultPrimary,
      ModalidadesSliceDefaultPrimaryModalidadesItem,
      ModalidadesSliceVariation,
      ModalidadesSliceDefault,
      ProcesoSlice,
      ProcesoSliceDefaultPrimary,
      ProcesoSliceDefaultPrimaryStepsItem,
      ProcesoSliceVariation,
      ProcesoSliceDefault,
      TerritorioSlice,
      TerritorioSliceDefaultPrimary,
      TerritorioSliceVariation,
      TerritorioSliceDefault,
      DetalleEditorialSlice,
      DetalleEditorialSliceDefaultPrimary,
      DetalleEditorialSliceVariation,
      DetalleEditorialSliceDefault,
      ConfianzaSlice,
      ConfianzaSliceDefaultPrimary,
      ConfianzaSliceDefaultPrimaryPillarsItem,
      ConfianzaSliceVariation,
      ConfianzaSliceDefault,
      ContactoSlice,
      ContactoSliceDefaultPrimary,
      ContactoSliceVariation,
      ContactoSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
