// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  confianza: dynamic(() => import("./Confianza")),
  contacto: dynamic(() => import("./Contacto")),
  detalle_editorial: dynamic(() => import("./DetalleEditorial")),
  hero: dynamic(() => import("./Hero")),
  manifiesto: dynamic(() => import("./Manifiesto")),
  modalidades: dynamic(() => import("./Modalidades")),
  proceso: dynamic(() => import("./Proceso")),
  rich_text: dynamic(() => import("./RichText")),
  territorio: dynamic(() => import("./Territorio")),
};
